version: '3.8'

services:
  angular-app:
    image: cloudminds.jfrog.io/cloud2025/tradex-frontend-a900001:1.9
    ports:
      - "4200:80"
    depends_on:
      - fmts-nodejs
      - spring-app
      - mid-nodejs
    
  # network_mode removed to use default bridge network
    # environment:
    #   API_BASE_URL: http://mid-nodejs:4000/


  fmts-nodejs:
    image: cloudminds.jfrog.io/cloud2025/tradex-fmts-a900001:1.0
    ports:
      - "3000:3000"
  # network_mode removed to use default bridge network

  mid-nodejs:
    image: cloudminds.jfrog.io/cloud2025/tradex-midtier-a900001:1.5
    ports:
      - "8080:8080"
    depends_on:
      - spring-app
      - fmts-nodejs
  # network_mode removed to use default bridge network
    # environment:
    #   BACKEND_URL: http://spring-app:8080/

  spring-app:
    image: cloudminds.jfrog.io/cloud2025/tradex-backend-a900001:1.7
    ports:
      - "8081:8081"
    depends_on:
      - fmts-nodejs
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@a900001-tradex-db.cj6ui28e0bu9.ap-south-1.rds.amazonaws.com:1521/ORCL
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: SR2025fmr
      # FMTS_URL: http://fmts-nodejs:3000/fmts
  # network_mode removed to use default bridge network