package com.example.tradex_service.Models;

import lombok.Data;

@Data
public class Preferences {

    private String clientId; // PK, same as client's ID

    // --- Dropdown values as simple strings ---
    private String purpose;       // e.g., "Retirement"
    private String risk;          // e.g., "High Risk"
    private String income;        // e.g., "0-20000"
    private String length;        // e.g., "0-5 years"

    // --- Checkbox value as boolean ---
    private boolean roboAdvisor;

    // Constructors, getters, and setters can be generated by Lombok's @Data annotation


}
